pg-facade:
  proxy:
    port: 5433
    parameter-status-override:
      "is_superuser" : "off"
      "in_hot_standby" : "off"
  orchestration:
    adapter: docker
    docker:
      docker-host: unix:///var/run/docker.sock
      postgres-network-name: pg-facade-postgres-network
      postgres-container-name: pg-facade-managed-postgres
      postgres-image-tag: "postgres:latest"
  postgres:
    pg-facade-user: postgres
    pg-facade-password: postgres
    pg-facade-database: postgres
    healthcheck:
      start-period: 100000000 #nanoseconds
      interval: 100000000 #nanoseconds
      timeout: 100000000 #nanoseconds
      retries: 100
      command: pg_isready

quarkus:
  http:
    port: 8080
  log:
    level: INFO
  devservices:
    enabled: false